game18xx.world = {
	angle:90,
	terrain:[],
	tiles:[
		{terrain:'grass', col:4, row:0, open:['n','m'], track:[['n'],['m']], stage:'grey'},
		{terrain:'grass', col:7, row:0, open:['n','m'], track:[['n','m']], stage:'grey'},
		{terrain:'grass', col:8, row:0, open:['n','m'], track:[['n'],['m']], stations:['CanPac'], stage:'grey'},
		{terrain:'grass', col:4, row:1, open:['i','k','n','m'], stations:['']},
		{terrain:'grass', col:5, row:1, open:['u','h','k','n','m']},
		{terrain:'grass', col:6, row:1, open:['h','k','n']},
		{terrain:'grass', col:7, row:1, open:['i','h','k','n','m'], stations:['']},
		{terrain:'grass', col:8, row:1, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:9, row:1, open:['u','h','k','n','m']},
		{terrain:'grass', col:10, row:1, open:['h','k','n','m']},
		{terrain:'grass', col:11, row:1, open:['h','n'], track:[['h'],['n']]},
		{terrain:'grass', col:2, row:2, open:['k','n','m']},
		{terrain:'grass', col:3, row:2, open:['i','h','k','n','m']},
		{terrain:'grass', col:4, row:2, open:['u','i','h','k','n']},
		{terrain:'grass', col:5, row:2, open:['u','i','h','k']},
		{terrain:'grass', col:6, row:2, open:['i','h'], track:[['h','i']]},
		{terrain:'grass', col:7, row:2, open:['u','i','k','n','m']},
		{terrain:'grass', col:8, row:2, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:9, row:2, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:10, row:2, open:['u','i','h','n']},
		{terrain:'grass', col:0, row:3, open:['k','m'], track:[['k'],['m']], stations:['']},
		{terrain:'grass', col:1, row:3, open:['h','k','n','m']},
		{terrain:'grass', col:2, row:3, open:['i','h','k','n','m']},
		{terrain:'grass', col:3, row:3, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:4, row:3, open:['u','i','h','k','n','m'], stations:['','']},
		{terrain:'grass', col:5, row:3, open:['h','k','n','m']},
		{terrain:'grass', col:6, row:3, open:['h','k','n','m'], track:[['h'],['n'],['k']], stations:['']},
		{terrain:'grass', col:7, row:3, open:['i','h','k','n','m']},
		{terrain:'grass', col:8, row:3, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:9, row:3, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:10, row:3, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:11, row:3, open:['h','n'], track:[['h','n']]},
		{terrain:'grass', col:0, row:4, open:['u','i','k','n','m']},
		{terrain:'grass', col:1, row:4, open:['u','i','h','k','n'], stations:['','']},
		{terrain:'grass', col:2, row:4, open:['u','i','h']},
		{terrain:'grass', col:3, row:4, open:['u','i'], track:[['u','i']]},
		{terrain:'grass', col:4, row:4, open:['u','i','k','n','m'], stations:['Erie','']},
		{terrain:'grass', col:5, row:4, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:6, row:4, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:7, row:4, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:8, row:4, open:['u','i','h','k','n','m'], stations:['NYC']},
		{terrain:'grass', col:9, row:4, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:10, row:4, open:['u','i','h','n','m'], track:[['i'],['m']], stations:['Boston']},
		{terrain:'grass', col:0, row:5, open:['i','k','m'], track:[['i'],['k'],['m']]},
		{terrain:'grass', col:1, row:5, open:['u','i','h','n','m'], stations:['']},
		{terrain:'grass', col:2, row:5, open:['n','m'], track:[['n'],['m']], stations:['C&O']},
		{terrain:'grass', col:3, row:5, open:['k','n','m']},
		{terrain:'grass', col:4, row:5, open:['i','h','k','n','m']},
		{terrain:'grass', col:5, row:5, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:6, row:5, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:7, row:5, open:['u','i','h','k','n','m'], stations:['']},
		{terrain:'grass', col:8, row:5, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:9, row:5, open:['u','i','h','k','n']},
		{terrain:'grass', col:10, row:5, open:['u','i','h','k'], stations:['']},
		{terrain:'grass', col:11, row:5, open:['u','h'], track:[['u','h']]},
		{terrain:'grass', col:0, row:6, open:['u','i','k','n','m']},
		{terrain:'grass', col:1, row:6, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:2, row:6, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:3, row:6, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:4, row:6, open:['u','i','h','k','n']},
		{terrain:'grass', col:5, row:6, open:['u','i','h','k','m']},
		{terrain:'grass', col:6, row:6, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:7, row:6, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:8, row:6, open:['u','i','h','n'], stations:['NNH','']},
		{terrain:'grass', col:0, row:7, open:['i','k','m']},
		{terrain:'grass', col:1, row:7, open:['u','i','h','k','n','m'], stations:['']},
		{terrain:'grass', col:2, row:7, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:3, row:7, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:4, row:7, open:['u','i','h','k','n','m'], stations:['']},
		{terrain:'grass', col:5, row:7, open:['h','k'], track:[['h','k'],['h'],['k']], stations:['PRR']},
		{terrain:'grass', col:6, row:7, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:7, row:7, open:['u','i','h','k','n','m'], stations:['']},
		{terrain:'grass', col:8, row:7, open:['u','i','h','n','m'], stations:['','']},
		{terrain:'grass', col:-1, row:8, open:['k'], track:[['k']]},
		{terrain:'grass', col:0, row:8, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:1, row:8, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:2, row:8, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:3, row:8, open:['u','i','h','k','n','m']},
		{terrain:'grass', col:4, row:8, open:['u','h','k','n','m']},
		{terrain:'grass', col:5, row:8, open:['i','h','k','n','m']},
		{terrain:'grass', col:6, row:8, open:['u','i','h','k','n'], track:[['n'],['k']], stations:['B&O']},
		{terrain:'grass', col:7, row:8, open:['u','i','h','k']},
		{terrain:'grass', col:8, row:8, open:['u','h'], track:[['h','u']]},
		{terrain:'grass', col:0, row:9, open:['i','k'], track:[['i'],['k']]},
		{terrain:'grass', col:1, row:9, open:['u','i','h','k']},
		{terrain:'grass', col:2, row:9, open:['u','i','h','k']},
		{terrain:'grass', col:3, row:9, open:['u','i','h','k']},
		{terrain:'grass', col:4, row:9, open:['u','i','h','k']},
		{terrain:'grass', col:5, row:9, open:['u','i','h','k','m']},
		{terrain:'grass', col:6, row:9, open:['u','i','h','n','m'], stations:['']},
		{terrain:'grass', col:5, row:10, open:['u','i'], track:[['u'],['i']]},
		{terrain:'grass', col:6, row:10, open:['u'], track:[['u']], stations:['']},
	]
};

// Defaults for Tile and Overlay Sprites
window.onReady(function() {
$.extend(game18xx.defaults, {
//	overlay:{outOfBoundsKill:true},
	tile:{}
});
});
