game18xx.world = {
	angle:90,
	terrain:['grass'],
	tiles:[
		{col:3, row:0, open:['m'], track:[['m']], trackLevel:5},
		{col:4, row:0, open:['n','m'], track:[['n'],['m']], trackLevel:5},
		{col:7, row:0, open:['n','m'], track:[['n','m']], trackLevel:5},
		{col:8, row:0, open:['n','m'], track:[['n'],['m']], stations:['CanPac'], trackLevel:5},
		{col:4, row:1, open:['u','i','k','n','m'], stations:['']},
		{col:5, row:1, open:['u','h','k','n','m']},
		{col:6, row:1, open:['h','k','n']},
		{col:7, row:1, open:['i','h','k','n','m'], stations:['']},
		{col:8, row:1},
		{col:9, row:1, open:['u','h','k','n','m'], towns:1},
		{col:10, row:1, open:['h','k','n','m']},
		{col:11, row:1, open:['h','n'], track:[['h'],['n']], trackLevel:5},
		{col:2, row:2, open:['k','n','m']},
		{col:3, row:2, open:['i','h','k','n','m']},
		{col:4, row:2, open:['u','i','h','k','n']},
		{col:5, row:2, open:['u','i','h','k']},
		{col:6, row:2, open:['i','h'], track:[['h','town','i']], towns:1, trackLevel:5},
		{col:7, row:2, open:['u','i','k','n','m']},
		{col:8, row:2},
		{col:9, row:2},
		{col:10, row:2, open:['u','i','h','n']},
		{col:0, row:3, open:['k','m'], track:[['k'],['m']], stations:[''], trackLevel:5},
		{col:1, row:3, open:['h','k','n','m'], towns:1},
		{col:2, row:3, open:['i','h','k','n','m']},
		{col:3, row:3},
		{col:4, row:3, stations:['','']},
		{col:5, row:3, open:['h','k','n','m'], towns:1},
		{col:6, row:3, open:['h','k','n','m'], track:[['h'],['n'],['k']], stations:[''], trackLevel:5},
		{col:7, row:3, open:['i','h','k','n','m']},
		{col:8, row:3},
		{col:9, row:3},
		{col:10, row:3},
		{col:11, row:3, open:['h','n'], track:[['h','n']], trackLevel:5},
		{col:0, row:4, open:['u','i','k','n','m']},
		{col:1, row:4, open:['u','i','h','k','n'], stations:['','']},
		{col:2, row:4, open:['u','i','h']},
		{col:3, row:4, open:['u','i'], track:[['u','i']], trackLevel:5},
		{col:4, row:4, open:['u','i','k','n','m'], stations:['Erie','']},
		{col:5, row:4},
		{col:6, row:4},
		{col:7, row:4},
		{col:8, row:4, stations:['NYC']},
		{col:9, row:4},
		{col:10, row:4, open:['u','i','m','n','h'], track:[['i'],['m']], stations:['Boston'], trackLevel:1, trackCode:'B'},
		{col:0, row:5, open:['i','k','m'], track:[['i'],['k'],['m']], trackLevel:5},
		{col:1, row:5, open:['u','i','h','n','m'], stations:['']},
		{col:2, row:5, open:['n','m'], track:[['n'],['m']], stations:['C&O'], trackLevel:5},
		{col:3, row:5, open:['k','n','m']},
		{col:4, row:5, open:['i','h','k','n','m'], towns:1},
		{col:5, row:5},
		{col:6, row:5},
		{col:7, row:5, stations:['']},
		{col:8, row:5},
		{col:9, row:5, open:['u','i','h','k','n'], towns:2},
		{col:10, row:5, open:['u','i','h','k'], stations:['']},
		{col:11, row:5, open:['u','h'], track:[['u','town','h']], trackLevel:5, towns:1},
		{col:0, row:6, open:['u','i','k','n','m']},
		{col:1, row:6},
		{col:2, row:6, towns:2},
		{col:3, row:6},
		{col:4, row:6, open:['u','i','h','k','n']},
		{col:5, row:6, open:['u','i','h','k','m']},
		{col:6, row:6},
		{col:7, row:6},
		{col:8, row:6, open:['u','i','h','n'], track:[['n'],['i']], trackLevel:1, stations:['NNH','']},
		{col:0, row:7, open:['i','k','m'], towns:2},
		{col:1, row:7, stations:['']},
		{col:2, row:7},
		{col:3, row:7},
		{col:4, row:7, stations:['']},
		{col:5, row:7, open:['h','k'], track:[['k','h'],['h'],['k']], stations:['PRR'], trackLevel:5},
		{col:6, row:7},
		{col:7, row:7, stations:['']},
		{col:8, row:7, open:['u','i','h','n','m'], stations:['','']},
		{col:-1, row:8, open:['k'], track:[['k']], trackLevel:5},
		{col:0, row:8},
		{col:1, row:8},
		{col:2, row:8},
		{col:3, row:8},
		{col:4, row:8, open:['u','h','k','n','m']},
		{col:5, row:8, open:['i','h','k','n','m']},
		{col:6, row:8, open:['u','i','h','k','n'], track:[['n'],['k']], stations:['B&O'], trackLevel:1, trackCode:'B'},
		{col:7, row:8, open:['u','i','h','k']},
		{col:8, row:8, open:['u','h'], track:[['h','town','u']], trackLevel:5, towns:1},
		{col:0, row:9, open:['i','k'], track:[['i'],['k']], trackLevel:5},
		{col:1, row:9, open:['u','i','h','k']},
		{col:2, row:9, open:['u','i','h','k']},
		{col:3, row:9, open:['u','i','h','k']},
		{col:4, row:9, open:['u','i','h','k']},
		{col:5, row:9, open:['u','i','h','k','m']},
		{col:6, row:9, open:['u','i','h','n','m']},
		{col:5, row:10, open:['u','i'], track:[['u'],['i']], trackLevel:5},
		{col:6, row:10, open:['u'], track:[['u']], stations:[''], trackLevel:5},
	]
};
game18xx.board = [];

// Defaults for Overlay Sprites
window.onReady(function() {
Object.extend(game18xx.defaults, {
//	overlay:{outOfBoundsKill:true},
	location:{terrain:'grass', open:['u','i','h','k','n','m']}
});
});

window.onReady(function() {
game18xx.world.tiles.forEach(function(t, i) {
	if (t.col == 7 && t.row == 8) {
		Object.extendIfEmpty(game18xx.world.tiles[i], {open:['u','i','h','k'], track:[['h','k']], trackLevel:1})
	} else if (t.col == 6 && t.row == 9) {
		Object.extendIfEmpty(game18xx.world.tiles[i], {open:['u','i','h','n','m'], stations:[''], track:[['n'],['i']], trackLevel:1})
	}
});
});
